export enum ActivityLogType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  UPLOAD = 'UPLOAD',
  DOWNLOAD = 'DOWNLOAD',
  SHARED_LINK_CREATED = 'SHARED_LINK_CREATED',
  ASSIGN = 'ASSIGN',
  PERMISSION_CREATED = 'PERMISSION_CREATED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
}
